name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: StudentDAO Tests
      id: studentdao-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: StudentDAO Tests
        setup-command: mvn -q clean install
        command: mvn -q test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        STUDENTDAO-TESTS_RESULTS: "${{steps.studentdao-tests.outputs.result}}"
      with:
        runners: studentdao-tests
